[Materials]
	#
	#List of heat source blocks used under Thermo Generator.
	#Block registry name = heat, eg: ["minecraft:lava=1000", "minecraft:magma_block=800"]
	#Min = 1, max = 900000000
	heatSources = ["minecraft:lava=1000", "minecraft:magma_block=800", "powah:blazing_crystal_block=2800"]
	#Enable this to allow other mods to add their heat source blocks. [default:true]
	heatBlocksAPI = true
	#
	#List of coolant fluids used in the Reactor and the Thermo Generator.
	#Fluid registry name = cooling per mb, eg: ["minecraft:water=1", "examplemod:fluid=-1"]
	#Less number more cold, min = -100, max = 1
	coolantFluids = ["minecraft:water=1"]
	#Enable this to allow other mods to add their coolant fluids. [default:true]
	coolantFluidsAPI = true