[Features]
	#Enable the Chunky Turtle or not.
	enableChunkyTurtle = false

[world]
	#Enable the villager structures for the computer scientist.
	enableVillagerStructures = false
	#Gives the ap documentation to new players on a world.
	givePlayerBookOnJoin = false

