boxLeftX = -1
boxBorderColor = "0"
boxFillColor = "0"
boxThickness = 0
[style]
	High = "gold"
	Name = "white"
	Warning = "yellow"
	Progress = "white"
	InfoImportant = "blue"
	Label = "gray"
	Error = "red,bold"
	#Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
	Obsolete = "gray,strikethrough"